In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [3]:
a=np.arange(10)

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
typea(a)

NameError: name 'typea' is not defined

In [ ]:
type(a)

In [6]:
a.ndim

1

In [8]:
a.shape

(10,)

In [10]:
b=np.array([[1,2,3,4,5,],[6,7,8,9,0]])

In [11]:
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [12]:
b.shape

(2, 5)

In [13]:
len(b)

2

In [15]:
b.ndim

2

# NUMPY FUNCTION


In [16]:
a=np.linspace(1,10,3)

In [17]:
a

array([ 1. ,  5.5, 10. ])

In [21]:
b=np.eye(3)

In [23]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
c=np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diag(c)

array([1, 2, 3, 4])

In [27]:
r1=np.random.rand(4)
r1
#gives uniform distribution

array([0.51363362, 0.59982505, 0.71208789, 0.48615377])

In [29]:
r2=np.random.randn(4)
r2
#gives gussioan distribution

array([-0.1505113 , -1.19838174, -1.02346236,  0.22551097])

In [31]:
a.dtype

dtype('float64')

In [32]:
z=np.arange(1,10,dtype="float")

In [33]:
z


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
z1=a.copy()

In [35]:
z1


array([ 1. ,  5.5, 10. ])

In [36]:
z1[2]=100

In [39]:
z1

array([  1. ,   5.5, 100. ])

In [38]:
a

array([ 1. ,  5.5, 10. ])

In [40]:
mask=(a>1)
extract_by_mask=a[mask]
extract_by_mask

array([ 5.5, 10. ])

In [44]:
a[[0,1]]=2,3

In [42]:
a

array([ 2.,  3., 10.])

# NUMPY DIFFERENT OPERATION

In [39]:
a=np.arange(1,10,1)

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [42]:
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
print(c.shape)
print(b.shape)

(9, 1)
(1, 9)


In [59]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [60]:
x=np.tile(np.arange(0,40,10),(3,1))

In [61]:
x

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [62]:
y=np.tile(np.arange(0,40,10),(3,2))

In [63]:
y

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [64]:
y.ravel()#FLATTEING

array([ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0,
       10, 20, 30,  0, 10, 20, 30])

In [65]:
y


array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [69]:
y.T

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [68]:
y.T.ravel()

array([ 0,  0,  0, 10, 10, 10, 20, 20, 20, 30, 30, 30,  0,  0,  0, 10, 10,
       10, 20, 20, 20, 30, 30, 30])

In [70]:
np.tile([1,2,3,4,5,6],(3,2))

array([[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]])

In [71]:
z1=np.arange(0,10)

In [72]:
z1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
z1.resize((2,5))

In [74]:
z1


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
z2=np.arange(0,10).reshape(2,5)

In [80]:
z2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
import numpy as np
a=np.array([2,3,5,7,8,4])
print(np.argsort(a))#index of sorted number
a

[0 1 5 2 3 4]


array([2, 3, 5, 7, 8, 4])

In [15]:
a=np.array([[1,3,2],[4,2,7],[7,5,9]])

In [16]:
a

array([[1, 3, 2],
       [4, 2, 7],
       [7, 5, 9]])

In [22]:
coln_ind=1
a[a[:,coln_ind].argsort()]

array([[4, 2, 7],
       [1, 3, 2],
       [7, 5, 9]])

In [24]:
a.ravel()

array([1, 3, 2, 4, 2, 7, 7, 5, 9])

In [21]:
a.ravel()[np.newaxis,:]

array([[1, 3, 2, 4, 2, 7, 7, 5, 9]])

In [44]:
a=np.array([])


In [46]:
x=np.array([[1,3],[4,2],[7,5]])
print(x.shape)

(3, 2)


In [47]:
diagonal=np.diag([1,2,3,4])

In [48]:
diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [49]:
np.diag(diagonal)

array([1, 2, 3, 4])